@startuml
'https://plantuml.com/class-diagram

interface org.apache.dubbo.common.extension.ExtensionAccessor
abstract class org.apache.dubbo.rpc.model.ScopeModel
class ApplicationModel
class FrameworkModel
class ModuleModel

org.apache.dubbo.common.extension.ExtensionAccessor <|-- org.apache.dubbo.rpc.model.ScopeModel
org.apache.dubbo.rpc.model.ScopeModel <|-- ApplicationModel
org.apache.dubbo.rpc.model.ScopeModel <|-- FrameworkModel
org.apache.dubbo.rpc.model.ScopeModel <|-- ModuleModel

@enduml