@startuml
'https://plantuml.com/sequence-diagram

autonumber

AbstractApplicationContext.refresh -> AbstractApplicationContext.refresh : prepareRefresh
AbstractApplicationContext.refresh -> AbstractApplicationContext.refresh : obtainFreshBeanFactory
AbstractApplicationContext.refresh -> AbstractApplicationContext.prepareBeanFactory : setBeanExpressionResolver\n设置beanFactory的表达式语言处理器，Spring3增加了表达式语言的支持\n默认可以使用#{bean.xxx}的形式来调用和注入相关属性值
AbstractApplicationContext.prepareBeanFactory -> AbstractApplicationContext.prepareBeanFactory : addPropertyEditorRegistrar\n添加默认的Bean属性解析\n可通过配置CustomEditorConfigurer自定义属性类型解析
AbstractApplicationContext.prepareBeanFactory -> AbstractApplicationContext.prepareBeanFactory : addBeanPostProcessor\n实现这些Aware接口的bean在被初始化之后，可以取得一些对应的资源
AbstractApplicationContext.prepareBeanFactory -> AbstractApplicationContext.prepareBeanFactory : beanFactory.ignoreDependencyInterface 上一步相关的aware（？）
AbstractApplicationContext.prepareBeanFactory -> AbstractApplicationContext.prepareBeanFactory : beanFactory.registerResolvableDependency 将beanFactory和当前context放入依赖注入缓存
AbstractApplicationContext.prepareBeanFactory -> AbstractApplicationContext.prepareBeanFactory : addBeanPostProcessor(new ApplicationListenerDetector) 检测ApplicationListener的实现类
AbstractApplicationContext.prepareBeanFactory -> AbstractApplicationContext.prepareBeanFactory : addBeanPostProcessor(new LoadTimeWeaverAwareProcessor) 支持LoadTimeWeaver功能（-javaagent）
AbstractApplicationContext.prepareBeanFactory -> AbstractApplicationContext.prepareBeanFactory : setTempClassLoader 无需LoadTimeWeaver的bean加载使用独立的classloader（不符合双亲委派）（？）
AbstractApplicationContext.prepareBeanFactory -> AbstractApplicationContext.prepareBeanFactory : Register default environment beans.
AbstractApplicationContext.prepareBeanFactory -> AbstractApplicationContext.prepareBeanFactory : prepareBeanFactory
AbstractApplicationContext.prepareBeanFactory --> AbstractApplicationContext.refresh : prepareBeanFactory
AbstractApplicationContext.refresh -> AbstractApplicationContext.refresh : postProcessBeanFactory
AbstractApplicationContext.refresh -> AbstractApplicationContext.refresh : invokeBeanFactoryPostProcessors
AbstractApplicationContext.refresh -> AbstractApplicationContext.refresh : registerBeanPostProcessors
AbstractApplicationContext.refresh -> AbstractApplicationContext.refresh : initMessageSource
AbstractApplicationContext.refresh -> AbstractApplicationContext.refresh : initApplicationEventMulticaster
AbstractApplicationContext.refresh -> AbstractApplicationContext.refresh : onRefresh
AbstractApplicationContext.refresh -> AbstractApplicationContext.refresh : registerListeners
AbstractApplicationContext.refresh -> AbstractApplicationContext.refresh : finishBeanFactoryInitialization
AbstractApplicationContext.refresh -> AbstractApplicationContext.refresh : finishRefresh

@enduml
