spring:
  application:
    name: my-client
  cloud:
    loadbalancer:
      retry:
        enabled: true
      configurations: optimized-zone-preference

server:
  port: 8082

microsphere:
  availability:
    zone: cn
  customized-loadbalancer:
    enabled: true