@startuml
|#AntiqueWhite|消费线程|
start
-[#black]-> insert | update | delete;
if (is delete ?) then (delete)
:消息过滤，不处理;
stop
else if (is update ?) then (update)
    if (业务是否关心) then (业务不关心
    (无线规格&used字段更新&赠送订单))
        stop
    endif
else (insert)
endif
:写入缓存池;
:消费完毕;
-[#black]-> 发起异步处理;
|写缓存线程池|
:写入缓存池，去重，
重复缓存以较新数
据为准，区分实时性
要求高的数据;
-[#red]-> 无需启动线程;
|读缓存线程（单线程）|
:自旋，拉取缓存
数据，保证优先写
入实时性要求高的
数据。;
|入库线程池|
:更新ES数据;
stop
@enduml