@startuml

    package "sdk" #DDDDDD {
        interface OrderService {
            Result createOrder(Input input);
        }
        interface BillingCenterService {
            Result createPayOrder(Input input);
        }
    }

@enduml